import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  await prisma.car.deleteMany();
  await prisma.banner.deleteMany();
  await prisma.review.deleteMany();

  // ─── 차량 ───────────────────────────────────────────────────────────
  await prisma.car.createMany({
    data: [
      // 경차
      {
        name: "레이",
        nameEn: "Ray",
        category: "경차",
        brand: "기아",
        monthlyPrice: 24,
        year: "2024년형",
        fuel: "가솔린",
        seats: 4,
        mileage: "2만km/년",
        contractTerms: "12/24/36개월",
        label: "인기",
        sortOrder: 1,
        description: "실용적인 박스형 경차. 넓은 실내공간과 낮은 유지비로 도심 이동에 최적입니다.",
        options: "후방 카메라, 블루투스, USB 충전, 에어백",
        deposit: "없음",
      },
      {
        name: "모닝",
        nameEn: "Morning",
        category: "경차",
        brand: "기아",
        monthlyPrice: 21,
        year: "2023년형",
        fuel: "가솔린",
        seats: 4,
        mileage: "2만km/년",
        contractTerms: "12/24/36개월",
        label: null,
        sortOrder: 2,
        description: "대한민국 경차 베스트셀러. 부담 없는 월 납입금으로 시작하는 첫 렌트.",
        options: "후방 카메라, 블루투스 오디오",
        deposit: "없음",
      },
      // 소형/준중형 세단
      {
        name: "아반떼",
        nameEn: "Avante",
        category: "소형/준중형 세단",
        brand: "현대",
        monthlyPrice: 30,
        year: "2024년형",
        fuel: "가솔린",
        seats: 5,
        mileage: "2만km/년",
        contractTerms: "12/24/36개월",
        label: "인기",
        sortOrder: 3,
        description: "합리적인 가격의 준중형 세단. 연비와 디자인 모두 우수한 베스트셀러.",
        options: "스마트 크루즈, 차선유지 보조, 후방 모니터",
        deposit: "없음",
      },
      {
        name: "K3",
        nameEn: "K3",
        category: "소형/준중형 세단",
        brand: "기아",
        monthlyPrice: 28,
        year: "2023년형",
        fuel: "가솔린",
        seats: 5,
        mileage: "2만km/년",
        contractTerms: "12/24/36개월",
        label: null,
        sortOrder: 4,
        description: "세련된 디자인의 준중형 세단. 실용성과 경제성을 동시에 갖췄습니다.",
        options: "후방 카메라, 블루투스, 앞좌석 열선",
        deposit: "없음",
      },
      // 중형/대형 세단
      {
        name: "쏘나타",
        nameEn: "Sonata",
        category: "중형/대형 세단",
        brand: "현대",
        monthlyPrice: 38,
        year: "2024년형",
        fuel: "가솔린",
        seats: 5,
        mileage: "2만km/년",
        contractTerms: "24/36/48개월",
        label: null,
        sortOrder: 5,
        description: "국민 중형 세단. 넓은 공간과 안정적인 주행 성능으로 장거리도 편안합니다.",
        options: "스마트 크루즈, 후방 모니터, 차선유지, 통풍시트",
        deposit: "없음",
      },
      {
        name: "그랜저",
        nameEn: "Grandeur",
        category: "중형/대형 세단",
        brand: "현대",
        monthlyPrice: 48,
        year: "2024년형",
        fuel: "가솔린",
        seats: 5,
        mileage: "2만km/년",
        contractTerms: "24/36/48개월",
        label: "인기",
        sortOrder: 6,
        description: "국내 최고 인기 대형 세단. 넓은 실내 공간과 편안한 승차감의 대명사.",
        options: "스마트 크루즈, 후방 모니터, 통풍시트, 파노라마 선루프",
        deposit: "없음",
      },
      // SUV
      {
        name: "투싼",
        nameEn: "Tucson",
        category: "SUV",
        brand: "현대",
        monthlyPrice: 43,
        year: "2024년형",
        fuel: "가솔린",
        seats: 5,
        mileage: "2만km/년",
        contractTerms: "24/36/48개월",
        label: null,
        sortOrder: 7,
        description: "콤팩트 SUV의 강자. 도심과 교외 모두 소화하는 만능 패밀리카.",
        options: "후방 모니터, 차선유지, 스마트 크루즈, 전방충돌방지",
        deposit: "없음",
      },
      {
        name: "싼타페",
        nameEn: "Santa Fe",
        category: "SUV",
        brand: "현대",
        monthlyPrice: 55,
        year: "2024년형",
        fuel: "디젤",
        seats: 7,
        mileage: "2만km/년",
        contractTerms: "24/36/48개월",
        label: "인기",
        sortOrder: 8,
        description: "패밀리 SUV의 대표 모델. 넓은 7인승 공간과 뛰어난 주행 안정성.",
        options: "7인치 클러스터, 스마트 크루즈, 전방충돌방지, 차로유지 보조",
        deposit: "없음",
      },
      // 승합/미니밴
      {
        name: "스타리아",
        nameEn: "Staria",
        category: "승합/미니밴",
        brand: "현대",
        monthlyPrice: 60,
        year: "2024년형",
        fuel: "디젤",
        seats: 9,
        mileage: "2만km/년",
        contractTerms: "24/36/48개월",
        label: "신차",
        sortOrder: 9,
        description: "미래지향적 디자인의 고급 승합차. 9인승으로 단체 이동에 최적.",
        options: "파워슬라이딩도어, 후방카메라, 2열 독립시트, HUD",
        deposit: "없음",
      },
      {
        name: "카니발",
        nameEn: "Carnival",
        category: "승합/미니밴",
        brand: "기아",
        monthlyPrice: 52,
        year: "2024년형",
        fuel: "디젤",
        seats: 9,
        mileage: "2만km/년",
        contractTerms: "24/36/48개월",
        label: "인기",
        sortOrder: 10,
        description: "9인승 미니밴의 압도적 강자. 대가족 또는 단체 이동 시 최고의 선택.",
        options: "파워슬라이딩도어, 후방모니터, 2열 독립시트, 스마트키",
        deposit: "없음",
      },
      // 수입/프리미엄
      {
        name: "E클래스",
        nameEn: "E-Class",
        category: "수입/프리미엄",
        brand: "Mercedes-Benz",
        monthlyPrice: 95,
        year: "2024년형",
        fuel: "가솔린",
        seats: 5,
        mileage: "2만km/년",
        contractTerms: "24/36/48개월",
        label: "신차",
        sortOrder: 11,
        description: "압도적인 존재감의 메르세데스 E클래스. 비즈니스와 격식을 갖춘 이동에.",
        options: "MBUX, 어댑티브 크루즈, 파킹 어시스트, 통풍 마사지 시트",
        deposit: "협의",
      },
      {
        name: "5시리즈",
        nameEn: "5 Series",
        category: "수입/프리미엄",
        brand: "BMW",
        monthlyPrice: 88,
        year: "2024년형",
        fuel: "가솔린",
        seats: 5,
        mileage: "2만km/년",
        contractTerms: "24/36/48개월",
        label: null,
        sortOrder: 12,
        description: "드라이버스 카의 정점, BMW 5시리즈. 스포티함과 럭셔리를 동시에.",
        options: "iDrive 8.5, 능동 주행 보조, HUD, 하만카돈 사운드",
        deposit: "협의",
      },
    ],
  });

  // ─── 배너 슬라이드 ────────────────────────────────────────────────────
  await prisma.banner.createMany({
    data: [
      {
        chipLabel: "월 렌트 시작가",
        chipPrice: "24만원~",
        caption: "경차 · 레이/모닝",
        carType: "compact",
        glow: "rgba(87,214,240,.28)",
        isActive: true,
        sortOrder: 1,
      },
      {
        chipLabel: "세단 렌트 시작가",
        chipPrice: "38만원~",
        caption: "세단 · 쏘나타/그랜저",
        carType: "sedan",
        glow: "rgba(61,139,255,.28)",
        isActive: true,
        sortOrder: 2,
      },
      {
        chipLabel: "SUV 렌트 시작가",
        chipPrice: "55만원~",
        caption: "SUV · 싼타페/투싼",
        carType: "suv",
        glow: "rgba(87,214,240,.22)",
        isActive: true,
        sortOrder: 3,
      },
      {
        chipLabel: "승합/미니밴 시작가",
        chipPrice: "52만원~",
        caption: "승합 · 카니발/스타리아",
        carType: "van",
        glow: "rgba(61,139,255,.22)",
        isActive: true,
        sortOrder: 4,
      },
    ],
  });

  // ─── 이용 후기 ────────────────────────────────────────────────────────
  await prisma.review.createMany({
    data: [
      {
        stars: 5,
        text: "장기렌트가 처음이라 걱정했는데, 궁금한 점을 먼저 설명해주셔서 안심하고 진행했습니다. 차량도 빠르게 받았어요.",
        name: "김○○ 고객님",
        detail: "그랜저 · 광주 서구",
        initial: "김",
        sortOrder: 1,
      },
      {
        stars: 5,
        text: "다른 곳보다 견적이 합리적이었고, 원하는 색상까지 잘 찾아주셨어요. 상담부터 인수까지 친절하게 진행해 주셔서 만족합니다.",
        name: "이○○ 고객님",
        detail: "싼타페 · 광주 북구",
        initial: "이",
        sortOrder: 2,
      },
      {
        stars: 5,
        text: "아이가 있어 승합차가 필요했는데 조건에 딱 맞는 차량을 추천받았습니다. 보험·정비까지 포함이라 신경 쓸 게 없어 편해요.",
        name: "박○○ 고객님",
        detail: "카니발 · 전남 나주",
        initial: "박",
        sortOrder: 3,
      },
      {
        stars: 5,
        text: "E클래스를 장기렌트로 이용 중인데 가격 대비 서비스가 너무 좋습니다. 담당자분이 계속 챙겨주셔서 든든해요.",
        name: "최○○ 고객님",
        detail: "E클래스 · 광주 남구",
        initial: "최",
        sortOrder: 4,
      },
    ],
  });

  console.log("✅ 시드 완료: 차량 12종 / 배너 4개 / 후기 4개");
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
